src/trust.rs
Apparently I don't cd around projects very often. The code relied on `.shadowenv.d` existing at the PWD.
* fixes #3
* fixes #4 
:tophat: worked. Haven't added good tests yet 🙈
=> Work correctly in subdirectories of projects

src/main.rs
Just copy/pasted from https://github.com/clap-rs/clap/issues/28 🤷‍♂️ 
`env!` runs at compile-time, 🎩 works.
fixes #8
=> report version from cargo.toml

sh/shadowenv.bash.in, sh/shadowenv.zsh.in, src/main.rs, src/output.rs
Anything that's going to fail meaningfully is going to do it on the other hooks as well. This will prevent a confusing UX case outlined in https://github.com/Shopify/shadowenv/issues/12
fixes #12
=> Suppress errors on bash's DEBUG and zsh's preexec_functions:

src/shadowenv.rs
Fix issue where prepending to empty MANPATH would leave default man paths unused. (https://shopify.slack.com/archives/C030RFPKD/p1554742195823500)
=> Preserve empty item in path list

docs/shadowlisp.md, src/lang.rs, src/shadowenv.rs
```
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
$ mkdir -p demo/.shadowenv.d
$ echo '(env/append-to-pathlist "PATH" "/sentinel")' > demo/.shadowenv.d/demo.lisp
$ cd demo
shadowenv failure: directory contains untrusted shadowenv program: shadowenv help trust to learn more.
$ shadowenv trust
activated shadowenv
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/sentinel
$ cd ..
deactivated shadowenv
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```
It's worth noting that the behaviour is already allowed, this just makes it easier and more clear:
```lisp
(if (null (env/get "PATH"))
(env/set "PATH" "/sentinel")
(env/set "PATH" (concat (env/get "PATH") ":/sentinel" )))
```
=> Add append_to_pathlist

sh/shadowenv.bash.in, sh/shadowenv.fish.in, sh/shadowenv.zsh.in, src/diff.rs, src/main.rs
~Must be invoked as `shadowenv diff $__shadowenv_data`, which is a
significant drawback.~
~@burke, was `$__shadowenv_data` left un-exported merely for cleanliness, or do to a security concern I'm not seeing?  What do you think of exporting it, allowing simply `shadowenv diff`?~
Added a shell function to add in `$__shadowenv_data`.
Closes #17
=> Add shadowenv diff

src/shadowenv.rs
The list of items in the path list was improperly being set to a list containing empty string (`[""]`) regardless of whether or not the path list was previously set. This change fixes the handling of unset path lists.
Before:
```
nil        =>  [""]
""         =>  [""]
"foo:bar"  =>  ["foo", "bar"]
```
After:
```
nil        =>  []
""         =>  [""]
"foo:bar"  =>  ["foo", "bar"]
```
Fixes https://github.com/Shopify/shadowenv/issues/37
=> Handle unset and empty properly.

src/shadowenv.rs
Fixes #37.
For removing "removing" from pathlist.
|Start|Current Result|Desired Result|
|-|-|-|
|`nil`|`""`|`nil`|
|`""`|`""`|`""`|
|`"removing:"`|`""`|`""`|
|`"removing"`|`""`|`nil`|
=> Handle unset and empty properly on removal

Cargo.lock, Cargo.toml
The signatory deps had their own dependencies no longer available from crates.io, which prevented building shadowenv on a fresh machine.  This bump has dependencies which are available.
=> Bump signatory deps

Cargo.lock, Cargo.toml, dev.yml, sh/shadowenv.bash.in, src/hash.rs, src/main.rs, src/trust.rs
Improving error message when copying/moving projects.
- `is_dir_trusted` does not blindly returns verifier errors, it now returns false
- fix to `shadowenv.bash.in` to pass `--silent` on `preexec` to avoid raising errors on `preexec` hooks
This fixes issue #30:
~/src/github.com/Shopify $ cp -a dev bar
~/src/github.com/Shopify $ cd bar
shadowenv failure: directory contains untrusted shadowenv program: shadowenv help trust to learn more.
~/src/github.com/Shopify/bar $ shadowenv trust
activated shadowenv (ruby:2.3.7)
~/src/github.com/Shopify/bar $
This PR also adds quickcheck tests for `Hash`.
=> Improving error message when copying/moving projects

.github/workflows/release.yml, .github/workflows/rust.yml
Use the components config from the rust action
Fixes:
```
error: component 'rustfmt' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel 'nightly'
```
I left https://github.com/Shopify/shadowenv/issues/59 open for future reference
=> Pin nightly to 2019-10-04

src/execcmd.rs, src/hook.rs, src/main.rs
This causes shadowenv exec to load the shadowenv from a given directory,
rather than the current directory, but still execute the command
provided from the current directory after loading that other
environment.
I've also removed the short form (-d) for shadowenv exec
--shadowenv-data, since it just became very confusing. I don't think
anyone was really using that, so removing it should be ok.
=> Implement `shadowenv exec --dir <dir>`:

docs/shadowlisp.md
As pointed out in #61, these are needlessly powerful. Since we don't actually have the ability to mask these in the implementation until #62 is addressed, the best we can do for now is to remove their docs.
Closes #63.
cc @Profpatsch
=> Undocument things that make shadowlisp turing complete

Cargo.lock, Cargo.toml, docs/integration.md, man/man1/shadowenv.1, sh/shadowenv.bash.in, sh/shadowenv.fish.in, sh/shadowenv.zsh.in, src/diff.rs, src/execcmd.rs, src/hook.rs, src/main.rs, src/shadowenv.rs
Not exporting `__shadowenv_data` can cause problems when the user uses tmux, among probably other issues. This was a bad idea from the start.
This will be a 2.0.0 release
=> Export __shadowenv_data

sh/shadowenv.bash.in, sh/shadowenv.fish.in, sh/shadowenv.zsh.in, src/cli.rs, src/execcmd.rs, src/hook.rs, src/main.rs
There are scenarios where the shadowenv's exported environment is carried forward to a new shell as expected but is modified by the new shell's initialization. In this case shadowenv would not update the environment since the working directory hasn't changed from the previous shell.
The example below shows what happens when the user defines a default ruby in their bashrc.
```
$ cat ~/.bashrc
chruby 2.7.0
$ dev cd web
activated shadowenv (node:v10.18.0, ruby:2.6.5)
$ ruby --version
ruby 2.6.5
$ bash -l
$ ruby --version
ruby 2.7.0
```
Some affected scenarios that I know of include:
- Starting a new shell from a project directory (as exampled above)
- Starting tmux from a project directory
- Starting an editor (vscode, vim...) from a project directory and using its built-in terminal
To …
=> Force hook on first run

src/hash.rs, src/lang.rs, src/loader.rs
with `some_dir/.shadowenv.d/custom.lisp`:
```lisp
(env/set "FOO" (expand-path "./bin"))
```
If you
```
cd some_dir
cd sub_dir
```
Everything worked as expected, since the source hash didn't change on the second cd, leaving the lisp unevaluated. But if instead you went directly
```
cd some_dir/sub_dir
```
Shadowenv would fail, as it would try to set FOO to the non-existant `some_dir/sub_dir/bin` instead of `some_dir/bin`.
So add the root dir to the source hash, since it should effect the results, and then perform the shadowlisp evaluation at the root dir.
Fixes #76.
=> Evaluate expand-path in the shadowenv root directory

src/execcmd.rs, src/features.rs, src/hook.rs, src/lang.rs, src/shadowenv.rs, src/undo.rs
- Refactored Shadowenv to be a  simpler object, making it easier to test
- Extracted the `RefCell` logic into a `ShadowenvWrapper`
- Added clippy suggestions
- remove unused getter on `Feature`
=> Add tests for lang.rs and shadowenv.rs

src/output.rs
For some people, having output on `cd` commands is a bit noisy.
This turns off the output of the happy path: I can assume that shadowenv did its thing unless it tells me it failed.
Messages about the directory not being trusted are still printed
=> Allow user to turn off "shadowenv [de]activated" prompts

.github/workflows/release.yml, .github/workflows/test.yml
Also switches to dtolnay/rust-toolchain since actions-rs/toolchain appears to be archived.
=> Add aarch64-unknown-linux-gnu to releases

sh/shadowenv.bash.in, sh/shadowenv.zsh.in, src/cli.rs, src/init.rs
I have a use-case where I'd prefer to include hookbook manually.
=> Add --no-hookbook flag to init

src/cli.rs, src/exec_cmd.rs, src/hook.rs, src/lang.rs, src/shadowenv.rs
This is mainly useful in conjunction with --force to allow tools to detect when shadowenv has been overridden, e.g. manually or accidentally when mixing it with other tools like nvm and chruby.
=> Add support for shadowenv hook --clobber

docs/shadowlisp.md, man/man5/shadowlisp.5, src/lang.rs
Expressions like (expand-path "~/does-not-exist") explode since
std::fs::canonicalize needs to point to a file that exists. In the vast
majority of cases this isn't desirable, nor is its behaviour of
resolving symlinks. Symlinks subtly break shadowenv's eval caching
mechanism because the value does not get updated if the symlink changes,
and shadowenv explodes if the there is a symlink loop. If people want
that behaviour for some reason I think we should expose it via a
different expression, or ideally people should canonicalize the paths
externally.
=> Don't explode when expand-path result is missing

man/man1/shadowenv.1, src/cli.rs
(Don't know if this is a regression or a bug in the docs. This would be to improve the docs if it's the latter...)
This change updates the documentation to be more explicit about where to put command and arguments for `shadowenv exec` (and fixing some typos).
The previous documentation suggested that program arguments need to be specified after a `--`. But it's actually both the command name and the arguments.
The old text:
```
$ shadowenv exec --help
...
USAGE:
shadowenv exec [OPTIONS] <child-argv0|child-argv> [child-argv0] [-- <child-argv>...]
ARGS:
<child-argv0>      If the command takes no arguments, it can be passed directly as the last arugment.
<child-argv>...    If the command requires arguments, they must all be passed after a --.
```
This is in contrast of how it actually works. …
=> Update documentation for `shadowenv exec`
